---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chendom.
--- DateTime: 2022/8/2 14:03
---
print("hello world!!!")
print("--------------循环结构------------------")
local i=0
local length=100;
while i<=length do
    print("i="..i)
    i=i+1
end
print("------------选择结构--------------------")
local age=40
local sex='male'
if age==40 and sex=='male' then
    print("中年男人")
elseif age>60 and male~='female' then
    print("old man!!!")
elseif age<20 then
    print("to young to simple!!!")
else
    print("Your age is:"..age.." sex:"..sex);
end
print("---------------for循环--------------------")
local sum = 0
for i=0,100,2 do
    sum=sum+i;
    print(sum)
end
arr={"zhangsan","0",1,2,3,4,5}
for i, v in ipairs(arr) do
    print("i="..i.."v="..v);
end
print("----------------------函数--------------------")
function show(x,y)
    return x+y
end
local a,b=10,20
local c= show(a,b);
print("c:"..c)

print("----------------------函数多个返回值--------------------")
function cal(x,y)
    return x+1,y+1
end
local v1,v2=30,40
local a1,a2=cal(v1,v2)
print("a1="..a1..",a2="..a2)
print("-----------------table----------------------------------")
person={name='zhangsan',age=18,height=178.6}
print("name:"..person.name.."age:"..person.age.."hight:"..person.age)
print("-------------------------array-------------------------")
arr = {"string", 100, "dog",function() print("wangwang!") return 1 end}
print(arr[4]())
for i, v in pairs(arr) do
    print(i,v)
end
print("-------------------------------成员定义------------------------------")
dog={name="阿黄",age=18}
function dog.eat(food)
    print(dog.name.."正在吃"..food)
end
dog.eat("屎")